### ISSUE TITLE
refactor 

### ISSUE THREAD

**Issue by Livenow14** [potados99/paint-gui#1]
refactoring이 되었네요. 
어떤 오류로 영역이 벗어났을때 segment fault가 났엇는지 알 수 있을까요?

**Comment by potados99** [comment]
안녕하세요! 

2019년 이후 코드에 가해진 변경은 없습니다! 

다만 당시 최신 release이던 [v1.1.1](https://github.com/potados99/paint-gui/releases/tag/v1.1.1)이 마지막 커밋(https://github.com/potados99/paint-gui/commit/30bc6527d70987a5c25e745c1af13daacad59858) 을 포함하지 않고 있어 이를 방금 발견한 직후 새로운 release [v1.1.2](https://github.com/potados99/paint-gui/releases/tag/v1.1.2)를 만들어 주었습니다.

해당 커밋(https://github.com/potados99/paint-gui/commit/30bc6527d70987a5c25e745c1af13daacad59858 )이 해결한 문제는 아래와 같습니다.

## 증상

Free draw 상태에서 도형을 그리면서 캔버스 영역을 벗어나도 입력한 도형이 UI 위에 그대로 표시됨.

## 원인

[display.c](https://github.com/potados99/paint-gui/blob/master/src/display.c) 파일 542줄 근처에서 free draw 연속 입력에 대해 display에 버퍼(transaction) 없이 direct mode로 쓰기를 허용한 것이 원인이었습니다.

~~~c
disp_set_direct(true);	
disp_draw_linep(context->last_x, context->last_y, x, y, context->draw_color);
disp_set_direct(false);
~~~

캔버스 바깥 영역으로의 픽셀 쓰기는 `disp_draw_*()` 함수가 아닌, display transaction을 commit하는 `_redraw_areap()` 함수에서 걸러냅니다. 따라서 `_redraw_areap()` 함수를 사용하지 않으면 영역 밖 그리기에 대한 예외 처리가 적용되지 않습니다.

## 해결

다른 도형 그리기와 마찬가지로, display에 변화를 가한 후 이를 commit하도록 변경하였습니다.

~~~c
disp_draw_linep(context->last_x, context->last_y, x, y, context->draw_color);
_redraw_areap(context, context->last_x, context->last_y, x, y);
~~~

**Comment by Livenow14** [comment]
아하 저번에 검사중 해결하셨던 부분을 커밋 하셨던 거네요. 
여전히 발전중이신거 같아요 :)

**Comment by potados99** [comment]
네 맞아요! 그때 급하게 해결한 부분입니다 ㅎㅎ    
칭찬 감사합니다 😊
